### ISSUE TITLE
Session keeps timing out

### ISSUE THREAD

**Issue by MelRemy** [datacamp/course-resources-ml-with-experts-budgets#5]
**Background:** 
For the last four exercises in "Machine Learning with the Experts: School Budgets", Chapter "Improving your model", I cannot submit my answer because the session just keeps timing out. If I refresh the page, even before I hit submit answer, the console shows the following error:

Traceback (most recent call last): 
File "<PEC>", line 81, in <module> 
df = pd.read_csv('https://s3.amazonaws.com/assets.datacamp.com/production/course_2533/datasets/TrainingSetSample.csv', index_col=0) 
File "<PEC>", line 562, in parser_f 
return _read(filepath_or_buffer, kwds) 
File "<PEC>", line 301, in _read 
compression=kwds.get('compression', None)) 
File "<PEC>", line 308, in get_filepath_or_buffer 
req = _urlopen(str(filepath_or_buffer)) 
File "<PEC>", line 163, in urlopen 
return opener.open(url, data, timeout) 
File "<PEC>", line 466, in open 
response = self._open(req, data) 
File "<PEC>", line 484, in _open 
'_open', req) 
File "<PEC>", line 444, in _call_chain 
result = func(*args) 
File "<PEC>", line 1297, in https_open 
context=self._context, check_hostname=self._check_hostname) 
File "<PEC>", line 1256, in do_open 
raise URLError(err) 
urllib.error.URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)>

**Replicate:**

I can confirm when inputting the accurate code to exercise: https://campus.datacamp.com/courses/machine-learning-with-the-experts-school-budgets/improving-your-model?ex=9

The system accepts the code, lets me know I've passed but when I check the outline of the course it resets back to looking as if I never submitted an answer for that exercise:

![screen shot 2018-08-07 at 11 21 47 am](https://user-images.githubusercontent.com/38881425/43785398-355d0cb2-9a34-11e8-893c-f1c15542d4b3.png)
![screen shot 2018-08-07 at 11 22 33 am](https://user-images.githubusercontent.com/38881425/43785403-3822efca-9a34-11e8-8088-04e0d1f996dd.png)

UID: 2341064
Zendesk: https://datacamp.zendesk.com/agent/tickets/109837

**Comment by MelRemy** [comment]
Confirmed by User this is now resolved
